
services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_QUORUM=1
      - REDIS_MASTER_HOST=localhost
      - REDIS_MASTER_SET=${REDIS_MASTER_SET}
    depends_on:
      - redis
    ports:
      - '26379:26379'
